services:

  mongo:
    image: mongo:latest
    container_name: capoot-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=capoot
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=customer_service
    volumes:
      - mongo-data:/data/db
    networks:
      - capoot-network

volumes:
  mongo-data:
  
networks:
  capoot-network:
    driver: bridge

